export function productPageTitle(pathname: string): string {
  if (pathname === '/me/worklog') return 'Work log'
  if (/^\/w\/[^/]+\/?$/.test(pathname)) return 'Dashboard'
  if (/\/settings\/profile\/?$/.test(pathname)) return 'Profile'
  if (/\/issues\/[^/]+\/?$/.test(pathname)) return 'Issue'
  if (/\/issues\/?$/.test(pathname)) return 'Issues'
  if (/\/sprints\/[^/]+\/?$/.test(pathname)) return 'Sprint'
  if (/\/sprints\/?$/.test(pathname)) return 'Sprints'
  if (/\/milestones\/[^/]+\/?$/.test(pathname)) return 'Milestone'
  if (/\/projects\/?$/.test(pathname)) return 'Projects'
  if (/\/feed\/?$/.test(pathname)) return 'Team feed'
  if (/\/mentions\/?$/.test(pathname)) return 'Mentions'
  if (/\/unlinked\/?$/.test(pathname)) return 'Unlinked PRs'
  if (/\/reports\/?$/.test(pathname)) return 'Reports'
  if (/\/admin\/?$/.test(pathname)) return 'Administration'
  return 'Page not found'
}
